#!/usr/bin/env python3
"""
Rebuild DBLP paper–venue MAGNN preprocess (var1–var3) with **train-only P–C edges**.

This patches the logic in ``preprocess_DBLP{1,2,3}.py`` without editing those files:
  - **P–C / 1–3** uses only ``train_pos`` (mapped local paper/conf ids), not the full ``pc`` table.
  - **Var2 only**: **C–R** conf–area pairs are derived from ``pc`` rows whose papers are in
    ``train_pos`` only (reduces auxiliary leakage vs using all papers).

Outputs (per variant):
  ``data/preprocessed/DBLP_lp_pc_var{k}_train_pc/``

Run from the ``MAGNN`` directory (same as the original preprocess scripts).

Example:
  python preprocess_DBLP_pc_trainpc.py --variants v1,v2,v3
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
os.chdir(_THIS_DIR)

_VARIANT_FILES = {
    "v1": "preprocess_DBLP1.py",
    "v2": "preprocess_DBLP2.py",
    "v3": "preprocess_DBLP3.py",
}

_OUT = {
    "v1": "data/preprocessed/DBLP_lp_pc_var1_train_pc/",
    "v2": "data/preprocessed/DBLP_lp_pc_var2_train_pc/",
    "v3": "data/preprocessed/DBLP_lp_pc_var3_train_pc/",
}

# Exact slice replaced in all three scripts (paper–conference in adjacency).
_PC_OLD = """# P–C / 1-3
for p,c in pc[['paper_id','conf_id']].itertuples(index=False):
    if p in Pa_map and c in Co_map:
        pi,ci = A+Pa_map[p], A+P+T+Co_map[c]
        adjM[pi,ci] = 1
        adjM[ci,pi] = 1"""

_PC_NEW = """# P–C / 1-3 (train positives only — avoids paper–venue LP leakage)
for pL, cL in train_pos:
    pi, ci = A + int(pL), A + P + T + int(cL)
    adjM[pi, ci] = 1
    adjM[ci, pi] = 1"""

# Var2 only: conf–area edges from train papers only.
_CR_OLD = """# C–R / 3-4
cr = (pc[['paper_id','conf_id']]
        .drop_duplicates()
        .merge(pr[['paper_id','area_id']].drop_duplicates(), on='paper_id')
        [['conf_id','area_id']].drop_duplicates().reset_index(drop=True))"""

_CR_NEW = """# C–R / 3-4 (papers restricted to train P–C positives)
_train_pi = set(train_pos[:, 0].astype(int))
cr = (pc[pc['paper_id'].map(Pa_map).isin(_train_pi)][['paper_id','conf_id']]
        .drop_duplicates()
        .merge(pr[['paper_id','area_id']].drop_duplicates(), on='paper_id')
        [['conf_id','area_id']].drop_duplicates().reset_index(drop=True))"""


def _patch_source(text: str, variant: str) -> str:
    if _PC_OLD not in text:
        raise RuntimeError(
            "Patch failed: P–C block not found (file changed?). "
            "Expected the standard loop over pc[['paper_id','conf_id']]."
        )
    text = text.replace(_PC_OLD, _PC_NEW, 1)
    if variant == "v2":
        if _CR_OLD not in text:
            raise RuntimeError("Patch failed: C–R block not found in var2 template.")
        text = text.replace(_CR_OLD, _CR_NEW, 1)

    # Redirect output dir
    import re

    m = re.search(r"^OUT\s*=\s*['\"]([^'\"]+)['\"]", text, re.M)
    if not m:
        raise RuntimeError("Could not find OUT = '...' in template.")
    old_out = m.group(0)
    new_out = f"OUT = '{_OUT[variant]}'"
    text = text.replace(old_out, new_out, 1)
    return text


def _run_variant(variant: str) -> None:
    src_name = _VARIANT_FILES.get(variant)
    if not src_name:
        raise ValueError(f"Unknown variant {variant!r}; use v1, v2, or v3.")
    src_path = os.path.join(_THIS_DIR, src_name)
    if not os.path.isfile(src_path):
        raise FileNotFoundError(src_path)

    with open(src_path, "r", encoding="utf-8") as f:
        body = f.read()
    patched = _patch_source(body, variant)

    header = (
        f"# Generated by preprocess_DBLP_pc_trainpc.py — do not edit by hand.\n"
        f"# variant={variant} source={src_name}\n\n"
    )
    fd, tmp_path = tempfile.mkstemp(suffix=f"_trainpc_{variant}.py", dir=_THIS_DIR, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as out:
            out.write(header)
            out.write(patched)
        print(f"\n=== Running patched preprocess | {variant} -> {_OUT[variant]} ===\n", flush=True)
        subprocess.run([sys.executable, tmp_path], cwd=_THIS_DIR, check=True)
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


def main():
    ap = argparse.ArgumentParser(description="DBLP MAGNN preprocess with train-only P–C (var1–v3).")
    ap.add_argument(
        "--variants",
        default="v1,v2,v3",
        help="Comma-separated: v1,v2,v3",
    )
    args = ap.parse_args()
    variants = [v.strip().lower() for v in args.variants.split(",") if v.strip()]
    for v in variants:
        _run_variant(v)
    print("\nAll requested variants finished.", flush=True)


if __name__ == "__main__":
    main()
